export default {
  ROLES: {
    ATTENDEE: "ATTENDEE",
    STAFF: "STAFF",
    ORGANIZER: "ORGANIZER",
    ADMIN: "ADMIN",
  },

  EVENT_STATUS: {
    DRAFT: "DRAFT",
    PUBLISHED: "PUBLISHED",
    ACTIVE: "ACTIVE",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
  },

  TICKET_STATUS: {
    UNUSED: "UNUSED",
    USED: "USED",
    REVOKED: "REVOKED",
  },

  CHECKIN_RESULT: {
    VALID: "VALID",
    DUPLICATE: "DUPLICATE",
    INVALID: "INVALID",
  },

  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
  },

  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
  },

  RATE_LIMIT: {
    WINDOW_MS: 15 * 60 * 1000,
    MAX_REQUESTS: 100,
    LOGIN_MAX: 5,
  },

  JWT: {
    ACCESS_EXPIRY: "30m",
    REFRESH_EXPIRY: "7d",
  },

  QR: {
    EXPIRY_HOURS: 24,
    SIZE: 300,
    MAX_SIZE: 1000,
  },

  UPLOAD: {
    MAX_SIZE: 5 * 1024 * 1024,
    ALLOWED_EXTENSIONS: [".csv", ".xlsx", ".pdf", ".docx"],
    DIR: "uploads",
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
};
